---
title: "Paquetes ggplot2 y dplyr"
author: "Enrique Reyes"
date: "2/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Graficas en ggplot
## Ejemplo 1
```{r}
# Cargamos el paquete ggplot2
library(ggplot2)
# Cargamos el entorno
ggplot(data = iris, aes(Sepal.Length,Petal.Length))

# Agregamos lineas en vez de puntos
ggplot(data = iris, aes(Sepal.Length,Petal.Length))+
  geom_line()

# Pintamos las lineas por clase
ggplot(data=iris,aes(Sepal.Length,Petal.Length,color=Species))+
  geom_line()

# Agregamos puntos al entorno
ggplot(data = iris, aes(Sepal.Length,Petal.Length))+
  geom_point()

# Pintamos los puntos por clase
ggplot(data=iris,aes(Sepal.Length,Petal.Length,color=Species))+
  geom_point()

# Puntos y ajuste
ggplot(data = iris, aes(Sepal.Length,Petal.Length))+
  geom_point() + stat_smooth()

# Puntos y ajuste por clases
ggplot(data = iris,aes(Sepal.Length,Petal.Length,color=Species))+
  geom_point() + stat_smooth()

# Puntos y ajuste por clases sin bandas de confianza
ggplot(data=iris,aes(Sepal.Length,Petal.Length,color=Species))+
  geom_point() + stat_smooth(se=FALSE)

# Ajuste global con puntos por clase
ggplot(data=iris)+
  geom_point(aes(x=Sepal.Length, 
  y=Petal.Length, color=Species))+
  stat_smooth(aes(x=Sepal.Length,
  y=Petal.Length))

# Grafica con puntos de distinto tamaño
ggplot(data=iris,aes(Sepal.Length,Petal.Length,size=Species))+
  geom_point() + stat_smooth()

# Grafica con puntos de distnto tamaño y distinto color
ggplot(data=iris,aes(Sepal.Length,Petal.Length,color=Species,size=Species))+
  geom_point() + stat_smooth()

# Agrego trasnparencias
ggplot(data = iris, aes(Sepal.Length,Petal.Length,size=Petal.Width))+
  geom_point(alpha=0.7) + stat_smooth()

# Agrupar por forma, color 
ggplot(data = iris, aes(Sepal.Length,Petal.Length,shape=Species,color=Species))+
  geom_point(alpha=0.3) + stat_smooth()

# Agrupar por forma, color, con un tamaño mayor
ggplot(data = iris, aes(Sepal.Length,
      Petal.Length,shape=Species,
      color=Species,size=Species))+
  geom_point(alpha=0.7,size=3) + 
  stat_smooth()

# Graficas segmentadas
ggplot(data=iris,aes(Sepal.Length,Petal.Length,color=Species))+
  geom_point(alpha=0.7,size=3) +
  stat_smooth() +
  facet_wrap(~ Species)

# Boxplot
ggplot(data=iris,aes(iris$Species,Petal.Length))+
  geom_boxplot()

# Boxplot de color por clase
ggplot(data=iris,aes(iris$Species,Petal.Length,color=Species))+
  geom_boxplot()

# Agregamos a la grafica medidas calculadas a la grafica
ggplot(data=iris,aes(iris$Species,Petal.Length,color=Species))+
  geom_boxplot() +
  stat_summary(fun.y = mean, 
  geom="point",shape=18,size=3,color="black")

# Agregamos los puntos por grupo
ggplot(data=iris,aes(iris$Species,Petal.Length,color=Species))+
  geom_boxplot() + geom_jitter()

# Agregamos a la grafica medidas calculadas a la grafica y forma de moño
ggplot(data=iris,aes(iris$Species,Petal.Length,color=Species))+
  geom_boxplot(notch = TRUE) +
  stat_summary(fun.y = mean, 
  geom="point",shape=18,size=3,color="cyan3")+
  geom_jitter()

# Agregamos a la grafica medidas calculadas a la grafica y forma de violin
ggplot(data=iris,aes(iris$Species,Petal.Length,color=Species))+
  geom_violin() + geom_jitter(alpha=0.2) +
  stat_summary(fun.y = mean, 
  geom="point",shape=18,size=3,color="cyan3")

# Histogramas global
ggplot(data=iris, aes(Petal.Length)) + 
  geom_histogram()

# Histograma por clase
ggplot(data=iris, aes(Petal.Length,fill=Species)) + 
  geom_histogram()

# Histograma por clase y con transparencia
ggplot(data=iris, aes(Petal.Length,fill=Species)) + 
  geom_histogram(alpha=0.5)

# Diagramas de densidad
ggplot(data=iris, aes(Petal.Length,fill=Species)) + 
  geom_density(alpha=0.7)+
  ggtitle("Densidad")

# Qplot
qplot(Sepal.Length,Petal.Length,data=iris)

# Qplot por clases
qplot(Sepal.Length,Petal.Length,data=iris,color=Species)

# Qplot por clases y formas
qplot(Sepal.Length,Petal.Length,data=iris,color=Species,shape=Species)

# Qplot por clases, formas y tamaños
qplot(Sepal.Length,Petal.Length,data=iris,color=Species,
      shape=Species,size=Species)
qplot(Sepal.Length,Petal.Length,data=iris,color=Species,
      shape=Species,size=Petal.Width)

# Qplot por clases, formas, tamaños y transparencias
qplot(Sepal.Length,Petal.Length,data=iris,color=Species,
      shape=Species,size=Species,alpha=0.7)
qplot(Sepal.Length,Petal.Length,data=iris,color=Species,
      shape=Species,size=Petal.Width,alpha=0.8)

# Qplot por clases, formas, tamaños, transparencias y etiquetas
qplot(Sepal.Length,Petal.Length,data=iris,color=Species,
      shape=Species,size=Species,alpha=0.7,
      xlab="Sepal Length",ylab="Petal Length",
      main="Sepal vs Petal in Fisher Iris data")
```

## Ejemplo 2
```{r}
# Entorno
ggplot(data=mpg, aes(hwy,cty))

# Grafica de puntos
ggplot(data=mpg, aes(hwy,cty))+
  geom_point(aes(color=cyl))

# Grafica de puntos y ajuste lineal
ggplot(data=mpg, aes(hwy,cty)) +
  geom_point(aes(color=cyl)) +
  geom_smooth(method = "lm")

# Grafica de puntos, ajuste lineal y con tema diferente
ggplot(data=mpg, aes(hwy,cty)) +
  geom_point(aes(color=cyl)) +
  geom_smooth(method = "lm") +
  theme_minimal()

# Grafica con una variable continua
# Densidad empirica
ggplot(mpg,aes(hwy)) +
  geom_area(stat="bin")

# Densidad ajustada
ggplot(mpg,aes(hwy)) +
  geom_density(kernel="gaussian")

# Densidad por puntos
ggplot(mpg,aes(hwy)) +
  geom_dotplot()

# Frecuencia empirica
ggplot(mpg,aes(hwy)) +
  geom_freqpoly()

# Histogramas con mayor tamaño
ggplot(mpg,aes(hwy)) +
  geom_histogram(binwidth = 5)

# Grafica de barras
ggplot(mpg,aes(fl))+
  geom_bar()

# Grafica de serie
ggplot(economics,aes(date,unemploy)) +
  geom_path()

# Grafica de bandas
ggplot(economics,aes(date,unemploy)) +
  geom_ribbon(aes(ymin=unemploy-900,ymax=unemploy+900))

```

# Manejo de datos con dply

## Ejemplo
```{r}
# Cargamos el paquete
library(dplyr)

# Cargamos la base de ejemplo
lirios=iris
lirios

# filtro unico
filter(lirios,Species=="setosa")

# Dos opciones
filter(lirios,Species=="setosa" | Species=="virginica")
filter(lirios,Species=="setosa" & Petal.Width<0.3)
filter(lirios, Species=='setosa', Sepal.Length < 5)

# Seleccion de columnas
select(lirios, Sepal.Length, Sepal.Width)
select(lirios, Petal.Length:Sepal.Length)
select(lirios, -Species)
select(lirios, contains('Petal'))

# Ordenar filas de menor a mayor valor conforme una variable
arrange(lirios, Sepal.Length)
arrange(lirios, -Sepal.Length)
# Es posible ordenar respecto de una variable y resolver los empates de acuerdo con una segunda variable
arrange(lirios, Species, Sepal.Length)

# Sintaxis encadenada
lirios %>%
  select(contains('Petal'))  %>%
  filter(Petal.Length > 4)   %>%
  arrange(Petal.Length)

# Codigo anidado
arrange(filter(select(lirios, contains('Petal')), Petal.Length > 4), Petal.Length)

# Otro ejemplo de Sintaxis encadenada vs anidada
x1 <- 1:6; x2 <- 7:12

# Sintaxis anidada
sqrt(sum((x1-x2)^2))

# Sintaxis en cadena
(x1-x2)^2 %>% sum() %>% sqrt()

# Añadir nuevas variables
lirios %>%
  mutate(forma = Petal.Width/Petal.Length)

# Resumir sobconjuntos
lirios %>%
  group_by(Species) %>%
  summarise(mean(Petal.Length))


# Alternativa
lirios %>%
  group_by(Species) %>%
  summarise_each(funs(mean), contains('Petal'))

# Extraccion aleatoria
lirios %>% sample_n(4)
lirios %>% sample_frac(0.25, rep=TRUE)

# Estructura
glimpse(lirios)

```

